FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Install with very long timeout and higher retries
RUN pip install --default-timeout=2000 --retries 10 --index-url https://pypi.org/simple/ -r requirements.txt

COPY src/ src/
COPY config/ config/

EXPOSE 8501

CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
